Update DD

diff --git a/DD b/DD
--- a/DD
+++ b/DD
@@ -1,9 +1,18 @@
 #!/bin/sh
 
+clear
+
+echo "This is the DD script"
+
+echo "This script requires root privileges to eject drives"
+
+# Prompt for password
+echo "Enter your laptop's password"
+sudo -v
+
 echo "Warning: This script will wipe the drive you are targeting"
-echo 
 echo "Do you want to proceed? (Y/n)"
-read choice
+read -r choice
 
 choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')
 
@@ -12,17 +21,23 @@ if [ "$choice" = "n" ]; then
     exit 1
 fi
 
-echo "Enter your laptop's password"
-echo
-sudo echo
-
 echo "Please enter the path for your file"
-read path
+read -r path
 echo
-echo "Please enter the USB drive path you can find it by doing lsblk"
-read usbdrivepath
 
-sudo dd if=$path of=$usbdrivepath bs=4M status=progress && sync
+lsblk -o NAME
+
+echo "Please enter the USB drive path (e.g., /dev/sdX):"
+read -r usbdrivepath
+
+# Check if the USB drive path exists
+if [ ! -b "$usbdrivepath" ]; then
+    echo "Error: USB drive path '$usbdrivepath' does not exist or is not a block device."
+    exit 1
+fi
+
+# Perform the DD operation with progress and sync
+sudo dd if="$path" of="$usbdrivepath" bs=4M status=progress && sync
 
 echo ""
 echo "========= SUCCESS ==========="
